print("Please enter a character: ")
MY_CHAR = input()[0]

ASCII_UPPERCASE_A = 65
ASCII_UPPERCASE_Z = 90
ASCII_LOWERCASE_A = 97
ASCII_LOWERCASE_Z = 122

ASCII_MY_CHAR = ord(MY_CHAR)

IS_ALPHABET = True if ( (ASCII_MY_CHAR>=ASCII_UPPERCASE_A and ASCII_MY_CHAR<=ASCII_UPPERCASE_Z) or (ASCII_MY_CHAR>=ASCII_LOWERCASE_A and ASCII_MY_CHAR<=ASCII_LOWERCASE_Z) ) else False

print(f"Character: {MY_CHAR} is an alphabet = {IS_ALPHABET}")